[general]
import = [
    "~/.local/share/alacritty/themes/themes/solarized_dark.toml"
]

[window]
decorations = "Transparent"
padding = { x = 8, y = 6 }

[scrolling]
history = 100000

[font]
normal = { family = "FiraCode Nerd Font" }
size = 12

[cursor]
style = { shape = "Beam", blinking = "On" }

[terminal.shell]
program = "/opt/homebrew/bin/zsh"
args = [
  "-l",
  "-c",
  "/opt/homebrew/bin/tmux a -t scratch || /opt/homebrew/bin/tmux new -s scratch"
]
