# emacs package

[emacs-org-modern-indent]
src.git = "https://github.com/jdtsmith/org-modern-indent"
src.branch = "main"
fetch.github = "jdtsmith/org-modern-indent"

[emacs-astro-ts-mode]
src.git = "https://git.isincredibly.gay/srxl/astro-ts-mode.git"
src.branch = "master"
fetch.git = "https://git.isincredibly.gay/srxl/astro-ts-mode.git"

[emacs-lsp-proxy]
src.git = "https://github.com/jadestrong/lsp-proxy.git"
src.branch = "main"
fetch.github = "jadestrong/lsp-proxy"
cargo_lock = ["Cargo.lock"]

[emacs-ghostel]
src.git = "https://github.com/dakra/ghostel.git"
src.branch = "main"
fetch.github = "dakra/ghostel"

[emacs-ghostel-module]
src.github = "dakra/ghostel"
fetch.url = "https://github.com/dakra/ghostel/releases/latest/download/ghostel-module-aarch64-macos.dylib"
