# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  emacs-astro-ts-mode = {
    pname = "emacs-astro-ts-mode";
    version = "1d24c9d399dee4cfea6ed9b49d8e08891665e16c";
    src = fetchgit {
      url = "https://git.isincredibly.gay/srxl/astro-ts-mode.git";
      rev = "1d24c9d399dee4cfea6ed9b49d8e08891665e16c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-HN04hS5rS6wJ6XhN9sgVKtELFnw/teumIQM1cPD0pbI=";
    };
    date = "2026-04-17";
  };
  emacs-lsp-proxy = {
    pname = "emacs-lsp-proxy";
    version = "6e823791c9866064d309f5e624660bcfe4126f53";
    src = fetchFromGitHub {
      owner = "jadestrong";
      repo = "lsp-proxy";
      rev = "6e823791c9866064d309f5e624660bcfe4126f53";
      fetchSubmodules = false;
      sha256 = "sha256-jG9m5i7Yc+V46uR5PWKmPvIj8EwKDWBrSyPmmTR0wtc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-jG9m5i7Yc+V46uR5PWKmPvIj8EwKDWBrSyPmmTR0wtc=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-06-14";
  };
  emacs-org-modern-indent = {
    pname = "emacs-org-modern-indent";
    version = "ebf9a8e571db523dc6e4cd9ed80d0e0626983ae4";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "org-modern-indent";
      rev = "ebf9a8e571db523dc6e4cd9ed80d0e0626983ae4";
      fetchSubmodules = false;
      sha256 = "sha256-+q7KmbU8A+uR61BSa528vYbdFSj2WGsFWYW/5q7J9Kw=";
    };
    date = "2026-01-02";
  };
}
