# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  emacs-astro-ts-mode = {
    pname = "emacs-astro-ts-mode";
    version = "b9ba8559effbd0677838d1fda6599dece51499b8";
    src = fetchgit {
      url = "https://git.isincredibly.gay/srxl/astro-ts-mode.git";
      rev = "b9ba8559effbd0677838d1fda6599dece51499b8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-TTTfZN76x/wNuIXFttHwyDILHU9zjWaOKWIX2ODwtrI=";
    };
    date = "2026-07-07";
  };
  emacs-ghostel = {
    pname = "emacs-ghostel";
    version = "fd53e45e098e6efd8ce0dac29f23ddd1819b9695";
    src = fetchFromGitHub {
      owner = "dakra";
      repo = "ghostel";
      rev = "fd53e45e098e6efd8ce0dac29f23ddd1819b9695";
      fetchSubmodules = false;
      sha256 = "sha256-8SsW9viV/adnw85ZAqlHD6iJWNMPP+9idR8PF6Sv7Ak=";
    };
    date = "2026-08-12";
  };
  emacs-ghostel-module = {
    pname = "emacs-ghostel-module";
    version = "v0.49.0";
    src = fetchurl {
      url = "https://github.com/dakra/ghostel/releases/latest/download/ghostel-module-aarch64-macos.dylib";
      sha256 = "sha256-Brq06og1UVdtl4jIxCv9lzFPkBXWucIpQ0vgsuM0cWc=";
    };
  };
  emacs-lsp-proxy = {
    pname = "emacs-lsp-proxy";
    version = "45566dfe32ef31d71ac7d74fc18dd64a04cc82a5";
    src = fetchFromGitHub {
      owner = "jadestrong";
      repo = "lsp-proxy";
      rev = "45566dfe32ef31d71ac7d74fc18dd64a04cc82a5";
      fetchSubmodules = false;
      sha256 = "sha256-VmMwX+gs3zLSFoPLJZuEXBypVEfZRXSajX2HJaTDh9U=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-VmMwX+gs3zLSFoPLJZuEXBypVEfZRXSajX2HJaTDh9U=/Cargo.lock";
      outputHashes = {

      };
    };
    date = "2026-07-04";
  };
  emacs-org-modern-indent = {
    pname = "emacs-org-modern-indent";
    version = "86bd83ee1ad95f123810eb3b116beb543db1960a";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "org-modern-indent";
      rev = "86bd83ee1ad95f123810eb3b116beb543db1960a";
      fetchSubmodules = false;
      sha256 = "sha256-vQzYk5qejCBehpbxkMceOMsmeLyjnAstpezZw/ZR1jQ=";
    };
    date = "2026-07-21";
  };
}
