# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  emacs-astro-ts-mode = {
    pname = "emacs-astro-ts-mode";
    version = "886d692378d0da2071e710c1e6db02e5b2e0dd30";
    src = fetchgit {
      url = "https://git.isincredibly.gay/srxl/astro-ts-mode.git";
      rev = "886d692378d0da2071e710c1e6db02e5b2e0dd30";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DAHuFZX8sQVbTKU6ZnQkHEnFqcdicH9a4thpwxmdDR8=";
    };
    date = "2025-03-09";
  };
  emacs-fzf-native = {
    pname = "emacs-fzf-native";
    version = "b159c581699e0661da015a845760578598880307";
    src = fetchFromGitHub {
      owner = "dangduc";
      repo = "fzf-native";
      rev = "b159c581699e0661da015a845760578598880307";
      fetchSubmodules = false;
      sha256 = "sha256-ykLRASDpOJMIQvD5+xGyvsRmhtuRBuctUQcjOhRKypg=";
    };
    date = "2024-12-24";
  };
  emacs-lsp-biome = {
    pname = "emacs-lsp-biome";
    version = "9b3d523e3df2a9f686e1b15396987a0310b62a15";
    src = fetchFromGitHub {
      owner = "cxa";
      repo = "lsp-biome";
      rev = "9b3d523e3df2a9f686e1b15396987a0310b62a15";
      fetchSubmodules = false;
      sha256 = "sha256-SSqbr0HDosdWbaMduoTK10jrsR+ZzWgkaLj9tWkScGQ=";
    };
    date = "2025-11-19";
  };
  emacs-org-modern-indent = {
    pname = "emacs-org-modern-indent";
    version = "ebf9a8e571db523dc6e4cd9ed80d0e0626983ae4";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "org-modern-indent";
      rev = "ebf9a8e571db523dc6e4cd9ed80d0e0626983ae4";
      fetchSubmodules = false;
      sha256 = "sha256-+q7KmbU8A+uR61BSa528vYbdFSj2WGsFWYW/5q7J9Kw=";
    };
    date = "2026-01-02";
  };
  fish-autopair = {
    pname = "fish-autopair";
    version = "4d1752ff5b39819ab58d7337c69220342e9de0e2";
    src = fetchFromGitHub {
      owner = "jorgebucaran";
      repo = "autopair.fish";
      rev = "4d1752ff5b39819ab58d7337c69220342e9de0e2";
      fetchSubmodules = false;
      sha256 = "sha256-qt3t1iKRRNuiLWiVoiAYOu+9E7jsyECyIqZJ/oRIT1A=";
    };
    date = "2022-07-04";
  };
  fish-bd = {
    pname = "fish-bd";
    version = "ab686e028bfe95fa561a4f4e57840e36902d4d7d";
    src = fetchFromGitHub {
      owner = "0rax";
      repo = "fish-bd";
      rev = "ab686e028bfe95fa561a4f4e57840e36902d4d7d";
      fetchSubmodules = false;
      sha256 = "sha256-GeWjoakXa0t2TsMC/wpLEmsSVGhHFhBVK3v9eyQdzv0=";
    };
    date = "2022-03-04";
  };
  fish-done = {
    pname = "fish-done";
    version = "998ad4f5fc9cee36c09840a7e635b56428e554f9";
    src = fetchFromGitHub {
      owner = "franciscolourenco";
      repo = "done";
      rev = "998ad4f5fc9cee36c09840a7e635b56428e554f9";
      fetchSubmodules = false;
      sha256 = "sha256-GZ1ZpcaEfbcex6XvxOFJDJqoD9C5out0W4bkkn768r0=";
    };
    date = "2025-12-15";
  };
  fish-enhancd = {
    pname = "fish-enhancd";
    version = "5afb4eb6ba36c15821de6e39c0a7bb9d6b0ba415";
    src = fetchFromGitHub {
      owner = "babarot";
      repo = "enhancd";
      rev = "5afb4eb6ba36c15821de6e39c0a7bb9d6b0ba415";
      fetchSubmodules = false;
      sha256 = "sha256-pKQbwiqE0KdmRDbHQcW18WfxyJSsKfymWt/TboY2iic=";
    };
    date = "2025-01-24";
  };
  fish-fzf = {
    pname = "fish-fzf";
    version = "8920367cf85eee5218cc25a11e209d46e2591e7a";
    src = fetchFromGitHub {
      owner = "PatrickF1";
      repo = "fzf.fish";
      rev = "8920367cf85eee5218cc25a11e209d46e2591e7a";
      fetchSubmodules = false;
      sha256 = "sha256-T8KYLA/r/gOKvAivKRoeqIwE2pINlxFQtZJHpOy9GMM=";
    };
    date = "2024-04-06";
  };
  fish-ghq = {
    pname = "fish-ghq";
    version = "cafaaabe63c124bf0714f89ec715cfe9ece87fa2";
    src = fetchFromGitHub {
      owner = "decors";
      repo = "fish-ghq";
      rev = "cafaaabe63c124bf0714f89ec715cfe9ece87fa2";
      fetchSubmodules = false;
      sha256 = "sha256-6b1zmjtemNLNPx4qsXtm27AbtjwIZWkzJAo21/aVZzM=";
    };
    date = "2021-07-16";
  };
  zsh-autocomplete = {
    pname = "zsh-autocomplete";
    version = "bbba73ebdc7c01323e09d4d518e51e2d6847ccc2";
    src = fetchFromGitHub {
      owner = "marlonrichert";
      repo = "zsh-autocomplete";
      rev = "bbba73ebdc7c01323e09d4d518e51e2d6847ccc2";
      fetchSubmodules = false;
      sha256 = "sha256-998rYEyYD67XleSDbqvnQptRrGuG2N2AgFvTpFWvoV8=";
    };
    date = "2025-12-09";
  };
  zsh-enhancd = {
    pname = "zsh-enhancd";
    version = "5afb4eb6ba36c15821de6e39c0a7bb9d6b0ba415";
    src = fetchFromGitHub {
      owner = "babarot";
      repo = "enhancd";
      rev = "5afb4eb6ba36c15821de6e39c0a7bb9d6b0ba415";
      fetchSubmodules = false;
      sha256 = "sha256-pKQbwiqE0KdmRDbHQcW18WfxyJSsKfymWt/TboY2iic=";
    };
    date = "2025-01-24";
  };
  zsh-npm-scripts-autocomplete = {
    pname = "zsh-npm-scripts-autocomplete";
    version = "5d145e13150acf5dbb01dac6e57e57c357a47a4b";
    src = fetchFromGitHub {
      owner = "grigorii-zander";
      repo = "zsh-npm-scripts-autocomplete";
      rev = "5d145e13150acf5dbb01dac6e57e57c357a47a4b";
      fetchSubmodules = false;
      sha256 = "sha256-Y34VXOU7b5z+R2SssCmbooVwrlmSxUxkObTV0YtsS50=";
    };
    date = "2023-10-19";
  };
}
